apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-pod
spec:
  selector:
    app: nginx-pod
  #type: CluesterIP
  #type: NodePort
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80